### ISSUE TITLE
Exceeding a number of items inputed crashes the client

### ISSUE THREAD

**Issue by Ampflower** [Khazoda/basic-storage#1]
Hooking it up to CC's command computer to endlessly stuff stacks of chests into the barrel, came across a crash after it seemingly exceeded 1M.

Crash report in question:
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-07-20 21:46:36
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "java.util.Map$Entry.getKey()" because "e" is null
	at com.khazoda.basicstorage.util.NumberFormatter.format(NumberFormatter.java:27)
	at com.khazoda.basicstorage.renderer.CrateBlockEntityRenderer.renderText(CrateBlockEntityRenderer.java:120)
	at com.khazoda.basicstorage.renderer.CrateBlockEntityRenderer.renderCrateInfo(CrateBlockEntityRenderer.java:80)
	at com.khazoda.basicstorage.renderer.CrateBlockEntityRenderer.render(CrateBlockEntityRenderer.java:61)
	at com.khazoda.basicstorage.renderer.CrateBlockEntityRenderer.method_3569(CrateBlockEntityRenderer.java:33)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:368)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$bnp000$iris$addToList(SodiumWorldRenderer.java:584)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:307)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:270)
	at net.minecraft.class_761.handler$dcl000$sodium$onRenderBlockEntities(class_761.java:11827)
	at net.minecraft.class_761.method_22710(class_761.java:1119)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
	```

**Comment by khazoda** [comment]
@Ampflower 
This crash is likely related to my [NumberFormatter](https://github.com/Khazoda/basic-storage/blob/latest-stable/src/main/java/com/khazoda/basicstorage/util/NumberFormatter.java) class, but I'm not sure why it's throwing a null pointer exception. 

Would you be able to provide the code you're using in the CC computer to insert the stacks?
Thanks for the bug report, this is super helpful 👍

**Comment by Ampflower** [comment]
```lua
chest = peripheral.wrap("top") while true do commands.exec("item replace block ~ ~1 ~ container.0 with chest 64") chest.pushItems("right", 1) end
```

Which assumes some inventory (a chest was elected for this) on top and the crate to the right of the command computer.

One-liner so you can easily dump it into the `lua` command.

**Comment by Ampflower** [comment]
![image](https://github.com/user-attachments/assets/9cc30f58-ba32-46a3-a221-9533e78d1ebe)
You might be missing a zero in your if check, given that `M` starts at 1,000,000 while the the if cuts off at 100,000.

Tho I might recommend for the sake of less text is better is to start rounding off at 10,000 and have the decimal fill in the gap; you'll want to add in a `1_000, "K"` entry of course.

**Comment by khazoda** [comment]
Thank you, you're absolutely right I wasn't accounting for values above 100,000. I believe adding the following like you suggested should account for all numbers between 100,000 and 999,999
```java
suffixes.put(1_000, "K");
```
Values up to 100,000 I'm going to leave unabbreviated, as they don't clutter too much, and it's nice to see numbers go up.
Simultaneous insertion works too.

https://github.com/user-attachments/assets/1f1c1e33-62d4-40d4-890f-4e346cf8fa13

Thanks again for the bugfix, super helpful! Fixed in https://github.com/Khazoda/basic-storage/commit/8e090ec37b797c057ad58e33260c1815f3fc8572
